apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking
        image: siddhantchopra/booking-k8s-demo
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: mongodb+srv://siddhantchopra:siddhant17@cluster0.pyvptja.mongodb.net