apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: siddhantchopra/users-kube-demo
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: mongodb+srv://siddhantchopra:siddhant17@cluster0.pyvptja.mongodb.net