# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  hotel:
    # image: hotappreg.azurecr.io/apps/hotel
    build:
      context: .
      dockerfile: ./apps/hotel/Dockerfile
      target: development
    command: npm run start:dev hotel
    env_file:
      - ./apps/hotel/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
  users:
    # image: hotappreg.azurecr.io/apps/users
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
  booking:
    # image: hotappreg.azurecr.io/apps/users
    build:
      context: .
      dockerfile: ./apps/booking/Dockerfile
      target: development
    command: npm run start:dev booking
    env_file:
      - ./apps/booking/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
  # auth:
  #   build:
  #     context: .
  #     dockerfile: ./apps/auth/Dockerfile
  #     target: development
  #   command: npm run start:dev auth
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - ./apps/auth/.env
  #   depends_on:
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter
  #     - rabbitmq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'
  # mongodb-primary:
  #   image: docker.io/bitnami/mongodb:6.0
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
  #     - MONGODB_REPLICA_SET_MODE=primary
  #     - MONGODB_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123
  #   volumes:
  #     - 'mongodb_master_data:/bitnami/mongodb'
  #   ports:
  #     - '27017:27017'

  # mongodb-secondary:
  #   image: docker.io/bitnami/mongodb:6.0
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

  # mongodb-arbiter:
    # image: docker.io/bitnami/mongodb:6.0
    # depends_on:
    #   - mongodb-primary
    # environment:
    #   - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
    #   - MONGODB_REPLICA_SET_MODE=arbiter
    #   - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
    #   - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
    #   - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local